version: "3.9"
services:
  spicyuno.fun:
    build:
      args:
        ALPINE_VERSION: "latest"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "spicyuno:dev"
    image: "spicyuno:dev"
    ports:
      - "8080:8080/tcp"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/spicyuno.fun/container-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/spicyuno.fun/backup-volume
      

